version: "3"
services:
  prometheus:
    build:
      context: prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - monitoring
    environment:
      - HOST_IP_NOT_SET=${HOST_IP_NOT_SET:?Error HOST_IP_NOT_SET is not defined}
  grafana:
    build:
      context: grafana
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring
networks:
  monitoring:
    driver: bridge
