global:

# The root route on which each incoming alert enters.
route:
  group_by: [Alertname]
  # Send all notifications to me.
  receiver: sokar

receivers:
  - name: "sokar"
    webhook_configs:
      - url: http://localhost:11000/alerts
