dry-run: false
port: 11000
sca:
  mode: "job"
nomad:
  server-address: "http://192.168.0.236:4646"
job:
  name: "fail-service"
  min: 1
  max: 10
cap:
  down-scale-cooldown: 20s
  up-scale-cooldown: 10s
saa:
  no-alert-damping: 1.0
  up-thresh: 10.0
  down-thresh: -10.0
  eval-cycle: 1s
  eval-period-factor: 10
  cleanup-cycle: 60s
  alert-expiration-time: 5m
  scale-alerts:
    - name: "AlertA"
      weight: 1.5
      description: "Up alert"
    - name: "AlertB"
      weight: -1.5
      description: "Down alert"
logging:
  structured: false
  unix-ts: false
