dry-run: true
port: 12345
nomad:
  server-address: "http://192.168.0.236:4646"
job:
  name: "fail-service"
  min: 2
  max: 20
# CapacityPlanner
cap:
  down-scale-cooldown: 21s
  up-scale-cooldown: 12s
# ScaleAlertAggregator:
saa:
  no-alert-damping: 11.0
  up-thresh: 12.0
  down-thresh: -13.0
  eval-cycle: 14s
  eval-period-factor: 15
  cleanup-cycle: 16s
  scale-alerts:
    - name: "AlertA"
      weight: 1.5
      description: "Up alert"
    - name: "AlertB"
      weight: -1.5
      description: "Down alert"
logging:
  structured: true
  unix-ts: true
