dry-run: false
port: 11000
cap:
  down-scale-cooldown: 120s
  up-scale-cooldown: 60s
saa:
  no-alert-damping: 1.0
  up-thresh: 10.0
  down-thresh: -10.0
  eval-cycle: 1s
  eval-period-factor: 10
  cleanup-cycle: 60s
logging:
  structured: false
  unix-ts: false
